# Generated by Django 4.1.12 on 2023-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('jobprovider', 'Job Provider'), ('jobseeker', 'Job Seeker'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
