# Generated by Django 4.2.7 on 2023-11-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_providers',
            name='is_verified',
        ),
    ]
