# Generated by Django 4.2.7 on 2023-11-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_postjobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostJob',
        ),
    ]
