# Generated by Django 4.2.7 on 2023-11-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_delete_postjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjobs',
            name='salary',
        ),
        migrations.AddField(
            model_name='postjobs',
            name='max_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='postjobs',
            name='smin_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
