# Generated by Django 4.2.7 on 2023-11-14 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_remove_postjobs_salary_postjobs_max_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_providers',
            name='pro_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postjobs',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job_providers'),
        ),
    ]
