# Generated by Django 4.2.7 on 2023-11-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_job_providers_pro_id_alter_postjobs_pro_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjobs',
            old_name='smin_salary',
            new_name='min_salary',
        ),
    ]
