# Generated by Django 4.2.7 on 2023-11-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0013_user_otp_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_created_at',
        ),
    ]
