# Generated by Django 4.2.7 on 2023-12-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_alter_job_providers_status_savedjob_rating_applyjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='pro_id',
        ),
    ]
