# Generated by Django 5.0 on 2024-02-21 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_remove_rating_pro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('To be scheduled', 'To be scheduled'), ('Cancelled', 'Cancelled')], default='To be scheduled', max_length=20)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('helpline', models.BigIntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.applyjob')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.postjobs')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job_providers')),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job_seekers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
