# Generated by Django 5.0 on 2024-02-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_interview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interview',
            old_name='location',
            new_name='venue',
        ),
    ]
