# Generated by Django 5.0 on 2024-03-15 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0020_alter_postjobs_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScreening',
            fields=[
                ('resume_id', models.AutoField(primary_key=True, serialize=False)),
                ('resume_file', models.FileField(upload_to='resume_screening/resumes/')),
                ('job_role', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('score', models.FloatField(default=0.0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resume_screening/pdf/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.job_seekers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
