# Generated by Django 5.0 on 2024-03-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_resumescreening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumescreening',
            name='seeker_id',
        ),
    ]
